//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleDetail
    {
        public ArticleDetail()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ReserveSaleDetails = new HashSet<ReserveSaleDetail>();
            this.ReturnItemDetails = new HashSet<ReturnItemDetail>();
        }
    
        public int ID { get; set; }
        public int ArticleId { get; set; }
        public int ColorId { get; set; }
        public int Pairs { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Carton { get; set; }
        public int TotalStock { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ReserveSaleDetail> ReserveSaleDetails { get; set; }
        public virtual ICollection<ReturnItemDetail> ReturnItemDetails { get; set; }
    }
}
