//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerAccount
    {
        public BuyerAccount()
        {
            this.BuyerAccountDetails = new HashSet<BuyerAccountDetail>();
        }
    
        public int ID { get; set; }
        public int BuyerID { get; set; }
        public decimal OutStandingAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal TotalBalance { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual ICollection<BuyerAccountDetail> BuyerAccountDetails { get; set; }
    }
}
