//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerAccountDetail
    {
        public int ID { get; set; }
        public int BAccountID { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual BuyerAccount BuyerAccount { get; set; }
    }
}
