//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public Buyer()
        {
            this.BuyerAccounts = new HashSet<BuyerAccount>();
            this.Orders = new HashSet<Order>();
            this.CashRecieptDetails = new HashSet<CashRecieptDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerAccount> BuyerAccounts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<CashRecieptDetail> CashRecieptDetails { get; set; }
    }
}
