//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.ArticleDetails = new HashSet<ArticleDetail>();
        }
    
        public int ID { get; set; }
        public string ColorName { get; set; }
    
        public virtual ICollection<ArticleDetail> ArticleDetails { get; set; }
    }
}
