//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCategory
    {
        public CustomerCategory()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
