//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAccounts = new HashSet<CustomerAccount>();
            this.ReturnItems = new HashSet<ReturnItem>();
            this.Invoices = new HashSet<Invoice>();
            this.ReserveSales = new HashSet<ReserveSale>();
            this.CashRecieptDetails = new HashSet<CashRecieptDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> CustomerCategoryID { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CustomerCategory CustomerCategory { get; set; }
        public virtual ICollection<CustomerAccount> CustomerAccounts { get; set; }
        public virtual ICollection<ReturnItem> ReturnItems { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ReserveSale> ReserveSales { get; set; }
        public virtual ICollection<CashRecieptDetail> CashRecieptDetails { get; set; }
    }
}
