//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int CreatedBy { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AmountRecieved { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FreightAmount { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
