//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int ArticleID { get; set; }
        public int ArticleDetailID { get; set; }
        public Nullable<int> ArticlePairs { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ArticleDetail ArticleDetail { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
    }
}
