//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public bool ShowView { get; set; }
        public bool ShowAdd { get; set; }
        public bool ShowEdit { get; set; }
        public bool ShowDelete { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
