//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReserveSale
    {
        public ReserveSale()
        {
            this.ReserveSaleDetails = new HashSet<ReserveSaleDetail>();
        }
    
        public int ReserveSaleID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int CreatedBy { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AmountRecieved { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ReserveSaleDetail> ReserveSaleDetails { get; set; }
    }
}
