//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitShoesUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnItem
    {
        public ReturnItem()
        {
            this.ReturnItemDetails = new HashSet<ReturnItemDetail>();
        }
    
        public int ReturnItemID { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int CreatedBy { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> Claim { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ReturnItemDetail> ReturnItemDetails { get; set; }
    }
}
