//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPInvoiceDetail
    {
        public int ID { get; set; }
        public int BPInvoiceID { get; set; }
        public int BPArticleID { get; set; }
        public int BPArticleDetailID { get; set; }
        public int Pairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual BPArticle BPArticle { get; set; }
        public virtual BPArticleDetail BPArticleDetail { get; set; }
        public virtual BPInvoice BPInvoice { get; set; }
    }
}
