//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMInvoice()
        {
            this.CMInvoiceDetails = new HashSet<CMInvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int CreatedBy { get; set; }
        public decimal TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMInvoiceDetail> CMInvoiceDetails { get; set; }
    }
}
