//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMInvoiceDetail
    {
        public int ID { get; set; }
        public int CMInvoiceID { get; set; }
        public int CMArticleID { get; set; }
        public int CMArticleDetailID { get; set; }
        public int Pairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual CMArticle CMArticle { get; set; }
        public virtual CMArticleDetail CMArticleDetail { get; set; }
        public virtual CMInvoice CMInvoice { get; set; }
    }
}
