//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JPArticleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JPArticleDetail()
        {
            this.JPInvoiceDetails = new HashSet<JPInvoiceDetail>();
            this.JPReturnItemDetails = new HashSet<JPReturnItemDetail>();
        }
    
        public int ID { get; set; }
        public int JPArticleId { get; set; }
        public int ColorId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int TotalStock { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual JPArticle JPArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JPInvoiceDetail> JPInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JPReturnItemDetail> JPReturnItemDetails { get; set; }
    }
}
