//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JPInvoiceDetail
    {
        public int ID { get; set; }
        public int JPInvoiceID { get; set; }
        public int JPArticleID { get; set; }
        public int JPArticleDetailID { get; set; }
        public int Pairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual JPArticle JPArticle { get; set; }
        public virtual JPArticleDetail JPArticleDetail { get; set; }
        public virtual JPInvoice JPInvoice { get; set; }
    }
}
