//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOrderDetail
    {
        public int SPOrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int WHArticleID { get; set; }
        public int WHArticleDetailID { get; set; }
        public int Size6 { get; set; }
        public int Size7 { get; set; }
        public int Size8 { get; set; }
        public int Size9 { get; set; }
        public int Size10 { get; set; }
        public int Size11 { get; set; }
        public int Size12 { get; set; }
        public int Size13 { get; set; }
        public int Total { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual WHArticle WHArticle { get; set; }
        public virtual WHArticleDetail WHArticleDetail { get; set; }
    }
}
