//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSArticleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSArticleDetail()
        {
            this.TSInvoiceDetails = new HashSet<TSInvoiceDetail>();
            this.TSReturnItemDetails = new HashSet<TSReturnItemDetail>();
        }
    
        public int ID { get; set; }
        public int TSArticleId { get; set; }
        public int ColorId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int TotalStock { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual TSArticle TSArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSInvoiceDetail> TSInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSReturnItemDetail> TSReturnItemDetails { get; set; }
    }
}
