//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSInvoiceDetail
    {
        public int ID { get; set; }
        public int TSInvoiceID { get; set; }
        public int TSArticleID { get; set; }
        public int TSArticleDetailID { get; set; }
        public int Pairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual TSArticle TSArticle { get; set; }
        public virtual TSArticleDetail TSArticleDetail { get; set; }
        public virtual TSInvoice TSInvoice { get; set; }
    }
}
