//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSReturnItemDetail
    {
        public int ID { get; set; }
        public int TSReturnItemID { get; set; }
        public int ArticleID { get; set; }
        public int ArticleDetailID { get; set; }
        public int ArticlePairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual TSArticle TSArticle { get; set; }
        public virtual TSArticleDetail TSArticleDetail { get; set; }
        public virtual TSReturnItem TSReturnItem { get; set; }
    }
}
