//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public System.DateTime UserSince { get; set; }
        public bool IsActive { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> PreviousLogin { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int RoleID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
