//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHReturnItemDetail
    {
        public int ID { get; set; }
        public int WHReturnItemID { get; set; }
        public int ArticleID { get; set; }
        public int ArticleDetailID { get; set; }
        public int ArticlePairs { get; set; }
        public decimal Price { get; set; }
    
        public virtual WHArticle WHArticle { get; set; }
        public virtual WHArticleDetail WHArticleDetail { get; set; }
        public virtual WHReturnItem WHReturnItem { get; set; }
    }
}
